### PR TITLE
stats Clear race condition fix

### PR DESCRIPTION
**Pull request by karlmcguire**
Along with a small fix, I added `TestCacheMetricsClear` to simulate what I perceived as the issue in #92, which is:

**Goroutine 1:** Continuously calling cache.Get (incrementing metrics counters atomically)
**Goroutine 2:** Calls cache.Clear (calls collectMetrics() which creates a new metrics object and replaces the pointer in cache instance)

The simplest solution I could think of is reserving the collectMetrics() function for initialization, which performs well, but for the cache.Clear operation we should use the same metrics object and atomically zero all counters. This will allow us to keep the performance benefits of using a single atomic operation for metrics.Add calls and not having to use a mutex or channel.

The downside to this solution is the possibility of metric inaccuracies because of the iterative nature of the metrics.Clear operation. Because metrics.Clear is not a single atomic operation, parallel calls to metrics.Add will continue to mutate the metrics object while it's being zeroed.

I do not foresee this downside causing any issues in the future because it would only occur in situations where cache.Clear is being called in parallel with other cache operations, so the user has presumably given up the expectation of fully accurate metrics and would be unable to measure the accuracy.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/93)

### CODE REVIEW

**Comment by ben-manes** [comment]
Why even clear metrics? Many reporting systems work better with monotonically incrementing counts, which defers the rollups (e.g. 5/10/15m) to their time-series database, which can then calculate the delta from the raw stats. If clear / rollups / etc are needed client-side then this can be done on-top, e.g. by baselining on a snapshot to diff against. Then only handling overflow is necessary.

**Comment by karlmcguire** [comment]
> Why even clear metrics?

That's actually a good question. I will bring it up with Badger team and see.

**Comment by karlmcguire** [comment]
@ben-manes I assume on overflow all metrics need to be reset?

**Comment by ben-manes** [comment]
Once it overflows a 64-bit counter it is probably not worth worrying too much about. Instead when making the snapshot we simply convert a negative value to the maximum. 2^63 is quite large so it wasn't worth worrying and over complicating it. (see [ConcurrentStatsCounter](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/stats/ConcurrentStatsCounter.java) if interested)

For reference, @manishrjain should remember Borgmon which assumed monatomic counters.

**Comment by jarifibrahim** [comment]
@karlmcguire I'm seeing the same race condition with this PR also https://teamcity.dgraph.io/viewLog.html?buildId=29750&buildTypeId=Badger_UnitTests .

**Comment by jarifibrahim** [comment]
The fix works fine in badger https://github.com/dgraph-io/badger/pull/1099

**Pull request merged**
