### PR TITLE
remove glog dependency

### PR DESCRIPTION
**Pull request by jhawk28**
updated go mod deps

glog adds global flags so it is not a good library (adding to an existing program causes a panic if a flag name conflicts)

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/293)

### CODE REVIEW

**Comment by jhawk28** [comment]
lol, just saw: https://github.com/dgraph-io/ristretto/pull/292

**Comment by David-Mao** [comment]
> Can we please merge this. Glog spins off a go routine that cannot be closed on it's `init()` function, breaking unit tests that check for go routine leaks.

Ditto. @mangalaman93

**Comment by mholt** [comment]
Glog is not intended for use outside Google:

> The repository contains an open source version of the log package used inside Google. The master copy of the source lives inside Google, not here. The code in this repo is for export only and is not itself under development. Feature requests will be ignored.

Why is this PR still unmerged??

**Comment by manishrjain** [comment]
@mholt , I maintain a fork of ristretto. I have this and other fixes, if you want to use that. I know Datadog uses my fork.

https://github.com/outcaste-io/ristretto/commit/bd658a460d49079c51c64cad7c1634c42df7a0ef

**Comment by mholt** [comment]
@manishrjain Thanks; since this is a dependency of a dependency of a ... (x4) ... I suppose I will use a `replace` in my go.mod -- that might do...

**Comment by mangalaman93** [comment]
@mholt will it be possible for you rebase it on latest `main` instead of `mater`. I already changed the base branch here to main. Apologies for the delay. Thanks

**Comment by mholt** [comment]
@mangalaman93 Thanks; this isn't my PR though, @jhawk28 would have to do that.

**Comment by jhawk28** [comment]
I did a rebase but it didn't appear to work correctly. I would recommend just creating another PR.

**Comment by jhawk28** [comment]
submitted a new pr #350

**Pull request closed without merging**
