### PR TITLE
fix: race in close

### PR DESCRIPTION
**Pull request by StarpTech**
Related: https://github.com/dgraph-io/ristretto/pull/294

Fixes: https://github.com/dgraph-io/ristretto/issues/377

### CODE REVIEW

**Comment by mangalaman93** [comment]
Hi @StarpTech, Thanks for the PR. Apologies for the delay. Would it be possible for you to explain/use the `sync/atomic` package instead?

**Comment by StarpTech** [comment]
@mangalaman93 no opinion on it. I copied the code from the previous contribution. I can also use the std library.

**Comment by mangalaman93** [comment]
Yes, please. Std Library is perfect.

**Comment by StarpTech** [comment]
I already used but I did not tidy. Please recheck.

**Review by mangalaman93 — APPROVED** [review]

**Pull request merged**
