### PR TITLE
remove glog dependency

### PR DESCRIPTION
**Pull request by jhawk28**
updated go mod deps

glog adds global flags so it is not a good library (adding to an existing program causes a panic if a flag name conflicts)

### CODE REVIEW

**Comment by mholt** [comment]
Thank you for making this :pray:

**Review by mangalaman93 — APPROVED** [review]

**Comment by mangalaman93** [comment]
Thanks for updating the PR. Merged.

**Comment by jackcipher** [comment]
Hi maintainers,

I noticed that pull request #350 was merged yesterday, but a new tag has not been released yet.Without a new tag, I can't update my go mod.Would you please release a new tag?

**Comment by mholt** [comment]
@jackcipher FYI you can always do `go get <module>@<commit>` even if there is not a tag yet :blush:

**Pull request merged**
