### PR TITLE
Added Simple Github CI Workflow

### PR DESCRIPTION
**Pull request by tchaudhry91**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/48)

### CODE REVIEW

**Comment by tchaudhry91** [comment]
https://github.com/dgraph-io/ristretto/issues/15
For the issue above. I can write Travis or other service too. Just let me know if there is a preference.
For now, this only runs Tests (with race detector, and they seem to be warning)
A linter can also be added. Let me know if there is a preference there.

**Comment by jarifibrahim** [comment]
@tchaudhry91 I don't see CI running on this PR. Does it have to be enabled manually?

**Comment by tchaudhry91** [comment]
@jarifibrahim Yes, normally actions have to enabled in the repository "Settings".
If the repo isn't eligible for actions yet, we can setup on something external I suppose.
It does trigger properly once actions are enabled: See the integration on the PR in my fork. 
https://github.com/tchaudhry91/ristretto/pull/1

**Comment by jarifibrahim** [comment]
@manishrjain @karlmcguire could one of you enable GitHub actions from the repository settings? I do not have access to the settings.

**Comment by jarifibrahim** [comment]
@tchaudhry91 The `git checkout` command on PR https://github.com/dgraph-io/ristretto/pull/57 seems to be failing and I guess it would fail for other PRs also. Can you please have a look?

**Comment by tchaudhry91** [comment]
@jarifibrahim 
Hey, 
It seems the failure was in go test only, not checkout. I assume this was discovered later in the PR you mentioned. I did check a couple of other PRs as well, the failure seems to be on the test stage only.
Let me know if there's still a problem.
Cheers!

**Pull request merged**
