### PR TITLE
basic lru with mutex. plan is to add batching on top

### PR DESCRIPTION
**Pull request by kk3399**
more details and planning here - https://github.com/dgraph-io/ristretto/issues/6

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/11)

### CODE REVIEW

**Comment by mangalaman93** [comment]
Seems like you will have to update the author in your commit. The user doesn't have an email (or the Github email) in the commit. That is why it is still complaining for signing CLA.

**Comment by mangalaman93** [comment]
And Golang CI is doing fine too https://golangci.com/r/github.com/dgraph-io/ristretto/pulls/11.
Your import doesn't look right. Instead of `ristretto/lru`, it should be `github.com/dgraph-io/ristretto/lru`.

**Comment by kk3399** [comment]
are you referring to import in cache.go file? if i change the import to "github.com/dgraph-io/ristretto/lru" it wont compile locally as it cant find the package there. are you saying that i should rename "ristretto/lru"?

**Comment by mangalaman93** [comment]
Yeah, I understand. It would be a bit tricky to handle this, given that go tools don't work well with forks. Let me walk you through the steps -
```
go get -d -u github.com/dgraph-io/ristretto
cd $GOPATH/src/github.com/dgraph-io/ristretto
git remote add fork git@github.com:kk3399/ristretto
git fetch -a
git rebase fork/master
```

Now, you can modify the import to `github.com/dgraph-io/ristretto/lru` from `ristretto/lru`. Let me know if any of the steps don't make sense

**Comment by kk3399** [comment]
so it's forking a fork. the steps are helpful 👍

**Pull request closed without merging**
