### PR TITLE
Fix crashing under ARMv6

### PR DESCRIPTION
**Pull request by XIELongDragon**
ristretto will crash under ARM32. It is caused by the function `goLoad64` at 

https://golang.org/src/runtime/internal/atomic/atomic_arm.go line 129

```go
//go:nosplit
func goLoad64(addr *uint64) uint64 {
	if uintptr(unsafe.Pointer(addr))&7 != 0 {
		*(*int)(nil) = 0 // crash on unaligned uint64
	}
	_ = *addr // if nil, fault before taking the lock
	var r uint64
	addrLock(addr).lock()
	r = *addr
	addrLock(addr).unlock()
	return r
}
```

The root cause is the `sampledLFU` unaligned

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/239)

### CODE REVIEW

**Comment by XIELongDragon** [comment]
```shell
goroutine 22 [running]:
runtime/internal/atomic.goLoad64(0x19b1744, 0x182bf9c, 0x3)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:131 +0x1c
github.com/dgraph-io/ristretto.(*sampledLFU).getMaxCost(...)
        /home/pi/neurons/vendor/github.com/dgraph-io/ristretto/policy.go:296
github.com/dgraph-io/ristretto.(*defaultPolicy).Add(0x19b1760, 0x3c60b443, 0x0, 0x38, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/neurons/vendor/github.com/dgraph-io/ristretto/policy.go:140 +0x80
github.com/dgraph-io/ristretto.(*Cache).processItems(0x191fc80)
        /home/pi/neurons/vendor/github.com/dgraph-io/ristretto/cache.go:435 +0x29c
created by github.com/dgraph-io/ristretto.NewCache
        /home/pi/neurons/vendor/github.com/dgraph-io/ristretto/cache.go:204 +0x32c

```

**Comment by XIELongDragon** [comment]
@jarifibrahim @manishrjain can you review please ?

**Review by jarifibrahim — APPROVED** [review]
@XIELongDragon apologies for the delay in review. Can you please add this comment https://github.com/dgraph-io/ristretto/pull/249/files#diff-2f3d176e1cb53549b532cb1313a54835140ac2ab5e3bbd6ea6b06f174ca5241dR282 ?

**Comment by XIELongDragon** [comment]
> @XIELongDragon apologies for the delay in review. Can you please add this comment https://github.com/dgraph-io/ristretto/pull/249/files#diff-2f3d176e1cb53549b532cb1313a54835140ac2ab5e3bbd6ea6b06f174ca5241dR282 ?

comments added

**Review by NamanJain8 — APPROVED** [review]

**Pull request merged**
