### PR TITLE
Delete .travis.yml

### PR DESCRIPTION
**Pull request by codeofnode**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/185)

### CODE REVIEW

**Comment by codeofnode** [comment]
> Travis CI should be removed only after TeamCity has been configured.

@jarifibrahim Teamcity has been configured https://teamcity.dgraph.io/viewType.html?buildTypeId=Ristretto_RistrettoBuild

**Review by jarifibrahim — APPROVED** [review]
Please create a `test.sh` script and then use that script in TeamCity. This provides us a way to run the test exactly similar to how CI is running them locally.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/185#-:-MFUlLQz0utWm1hp68Dz:b-rbsnx8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anurags92, @karlmcguire, @manishrjain, and @martinmr)

**Review by jarifibrahim — APPROVED** [review]
You'll need to sign the CLA as well.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/185#-:-MFUlgqY5j8T7ItT4RSy:bbeknem)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anurags92, @karlmcguire, @manishrjain, and @martinmr)

**Comment by codeofnode** [comment]
added the comments

```
# TEAMCITY_VERSION=local will avoid recursive calls, when it would be running in container
```

Read the updated file to get good context

Also changed the file mod now

**Comment by codeofnode** [comment]
In Teamcity, tests are run inside docker container.
And to bring exactly env as of CI, I thought it would be better to run in docker container itself, even when running locally.

when running local, one can also use local go with
```
TEAMCITY_VERSION=local ./test.sh
```

**Review by anurags92 — APPROVED** [review]

**Pull request merged**
