### PR TITLE
Improve memory performance

### PR DESCRIPTION
**Pull request by martinmr**
- Use an int64 instead of a time.Time struct to represent the time.
- By default, include the cost of the storeItem in the cost calculation.

Related to DGRAPH-1378

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/195)

### CODE REVIEW

**Review by manishrjain — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/195#-:-MHweGAD-X6qh4zUcXZi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anurags92 and @karlmcguire)

**Review by manishrjain — APPROVED** [review]
This is good to go.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/195#-:-MI5Y8_ECITVsUVd7KMy:b-ptbamt)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anurags92 and @karlmcguire)

**Comment by varun06** [comment]
@martinmr I have a test where I add a value to cache with TTL and then check for that value after TTL passed(say one second), that test is failing after this change(works fine with v0.0.3 ofc). I had to increase my wait time to make that test pass. I don't see any change that would do that in quick pass over code, but it would be a good idea to check SetWithTTL tests after this change.

**Comment by varun06** [comment]
Alright, so did some testing with couple sha's around this change, and this change definitely has some kind of regression with TTL.

**Comment by jarifibrahim** [comment]
hey @varun06 , can you share your test? Maybe send a PR to add it to ristretto? We can look at the failing test if this change has caused it.

**Comment by varun06** [comment]
sure @jarifibrahim 
going to replicate it this weekend and if it fails again, will send you the test...

**Comment by varun06** [comment]
@jarifibrahim This is the test that's failing

```
func TestRisPutGetOnExpiredItem(t *testing.T) {
	c, err := NewCache(10, 100, 1, false)
	if err != nil {
		t.Fatalf("cache creation error: %v", err)
	}

	value := []byte("my cache value")
	key := getCacheKey(t)
	keyStr := key.String()
	defer key.Close()

	// put
	err = c.Put(&key, bytes.NewBuffer(value), time.Now().Add(1*time.Second))
	if err != nil {
		t.Fatalf("key %s was not put", keyStr)
	}

	//wait for values to settle
	time.Sleep(10 * time.Millisecond)

	// get
	_, _, stat, err := c.Get(&key)
	if err != nil {
		t.Fatalf("key %s was not get", keyStr)
	}

	if stat != cutl.StatusPresent {
		t.Errorf("key %s expected to be 'present': got %q.", keyStr, stat)
	}

	// Wait for 1 second, item will expire
	time.Sleep(1 * time.Second)

	// verify item is missing
	_, _, stat, err = c.Get(&key)
	if err != nil {
		t.Fatalf("key %s was not get", keyStr)
	}

	if stat != cutl.StatusMissing {
		t.Errorf("key %s expected to be 'missing': got %s", keyStr, stat)
	}
}

```

```
=== RUN   TestRisPutGetOnExpiredItem
    ristretto_test.go:179: key 0#0#0#example.com/ expected to be 'missing': got PRESENT
--- FAIL: TestRisPutGetOnExpiredItem (1.01s)
```

**Comment by varun06** [comment]
so it seems that there is a regression when we use SetWithTTL.

**Comment by jarifibrahim** [comment]
Looks like I missed the replies. @varun06 the issue has been resolved now via https://github.com/dgraph-io/ristretto/pull/277 .
Apologies for the late reply.

**Pull request merged**
